{
  "env": {
    "_workflow_file_generator": "ci/gen-github-workflows.py"
  },
  "jobs": {
    "publish": {
      "environment": {
        "name": "pypi-release",
        "url": "https://pypi.org/p/rainwave-tools"
      },
      "name": "Publish the release package to PyPI",
      "permissions": {
        "id-token": "write"
      },
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Check out the repository",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Build and publish the package",
          "run": "sh ci/build-and-publish.sh"
        }
      ]
    }
  },
  "name": "Publish the release package to PyPI",
  "on": {
    "release": {
      "types": [
        "published"
      ]
    }
  }
}